"use strict";
var grannystore;
(function (grannystore) {
    function main() {
        let groceries = document.createElement("select");
        let bread = document.createElement("option");
        bread.innerHTML = "Bread";
        bread.setAttribute("name", "piece");
        groceries.appendChild(bread);
        let sausage = document.createElement("option");
        sausage.innerHTML = "Sausage";
        sausage.setAttribute("name", "piece");
        groceries.appendChild(sausage);
        let fish = document.createElement("option");
        fish.innerHTML = "Fish";
        fish.setAttribute("name", "kg");
        groceries.appendChild(fish);
        let cheese = document.createElement("option");
        cheese.innerHTML = "Cheese";
        cheese.setAttribute("name", "kg");
        groceries.appendChild(cheese);
        let drinks = document.createElement("select");
        let water = document.createElement("option");
        water.innerHTML = "Water";
        water.setAttribute("name", "bottles");
        drinks.appendChild(water);
        let beer = document.createElement("option");
        beer.innerHTML = "Beer";
        beer.setAttribute("name", "bottles");
        drinks.appendChild(beer);
        let milk = document.createElement("option");
        milk.innerHTML = "Milk";
        milk.setAttribute("name", "liter");
        drinks.appendChild(milk);
        let juice = document.createElement("option");
        juice.innerHTML = "Juice";
        juice.setAttribute("name", "bottle");
        drinks.appendChild(juice);
        let allGroceries = document.getElementById("groceries");
        allGroceries.appendChild(groceries);
        let groceriesCounter = document.createElement("input");
        groceriesCounter.setAttribute("type", "number");
        groceriesCounter.setAttribute("min", "1");
        groceriesCounter.setAttribute("max", "10");
        groceriesCounter.setAttribute("value", "1");
        groceriesCounter.setAttribute("name", "groceries");
        allGroceries.appendChild(groceriesCounter);
        let drinksCounter = document.createElement("input");
        drinksCounter.setAttribute("type", "number");
        drinksCounter.setAttribute("min", "1");
        drinksCounter.setAttribute("max", "10");
        drinksCounter.setAttribute("value", "1");
        drinksCounter.setAttribute("name", "drinks");
        let br = document.createElement("br");
        allGroceries.appendChild(br);
        allGroceries.appendChild(drinks);
        allGroceries.appendChild(drinksCounter);
        let mow = document.createElement("input");
        let label = document.createElement("label");
        label.innerHTML = "Mow the lawn 30€";
        label.setAttribute("for", "mow");
        mow.setAttribute("id", "mow");
        mow.setAttribute("type", "checkbox");
        mow.setAttribute("price", "30");
        mow.addEventListener("change", handleChange);
        label.appendChild(mow);
        let wiping = document.createElement("input");
        let wipingLabel = document.createElement("label");
        wipingLabel.innerHTML = "Wet wiping 50€";
        wipingLabel.setAttribute("for", "wiping");
        wiping.setAttribute("id", "wiping");
        wiping.setAttribute("type", "checkbox");
        wiping.setAttribute("price", "50");
        wiping.addEventListener("change", handleChange);
        wipingLabel.appendChild(wiping);
        let vacuum = document.createElement("input");
        let vacuumLabel = document.createElement("label");
        vacuumLabel.innerHTML = "Vacuum 30€";
        vacuumLabel.setAttribute("for", "vacuum");
        vacuum.setAttribute("id", "vacuum");
        vacuum.setAttribute("type", "checkbox");
        vacuum.setAttribute("price", "30");
        vacuum.addEventListener("change", handleChange);
        vacuumLabel.appendChild(vacuum);
        let post = document.createElement("input");
        let postLabel = document.createElement("label");
        postLabel.innerHTML = "Take care of post 10€";
        postLabel.setAttribute("for", "post");
        post.setAttribute("id", "post");
        post.setAttribute("type", "checkbox");
        post.setAttribute("price", "10");
        post.addEventListener("change", handleChange);
        postLabel.appendChild(post);
        let allHouseworks = document.getElementById("housework");
        allHouseworks.appendChild(label);
        allHouseworks.appendChild(wipingLabel);
        allHouseworks.appendChild(vacuumLabel);
        allHouseworks.appendChild(postLabel);
        let deposit = document.createElement("input");
        let depositLabel = document.createElement("label");
        depositLabel.innerHTML = "Deposit Money";
        depositLabel.setAttribute("for", "deposit");
        deposit.setAttribute("id", "deposit");
        deposit.setAttribute("type", "text");
        deposit.setAttribute("placeholder", "...€");
        depositLabel.appendChild(deposit);
        let withdraw = document.createElement("input");
        let withdrawLabel = document.createElement("label");
        withdrawLabel.innerHTML = "Withdraw Money";
        depositLabel.setAttribute("for", "withdraw");
        withdraw.setAttribute("id", "withdraw");
        withdraw.setAttribute("type", "text");
        withdraw.setAttribute("placeholder", "...€");
        withdrawLabel.appendChild(withdraw);
        let allMoney = document.getElementById("money");
        allMoney.appendChild(depositLabel);
        br = document.createElement("br");
        allMoney.appendChild(br);
        allMoney.appendChild(withdrawLabel);
        let card = document.createElement("input");
        let cardLabel = document.createElement("label");
        cardLabel.innerHTML = "Credit Card";
        depositLabel.setAttribute("for", "card");
        card.setAttribute("id", "card");
        card.setAttribute("type", "radio");
        card.setAttribute("name", "radio-group");
        cardLabel.appendChild(card);
        let paypal = document.createElement("input");
        let paypalLabel = document.createElement("label");
        paypalLabel.innerHTML = "PayPal";
        paypalLabel.setAttribute("for", "paypal");
        paypal.setAttribute("id", "paypal");
        paypal.setAttribute("type", "radio");
        paypal.setAttribute("name", "radio-group");
        paypalLabel.appendChild(paypal);
        let cash = document.createElement("input");
        let cashLabel = document.createElement("label");
        cashLabel.innerHTML = "Cash";
        cashLabel.setAttribute("for", "cash");
        cash.setAttribute("id", "cash");
        cash.setAttribute("type", "radio");
        cash.setAttribute("name", "radio-group");
        cashLabel.appendChild(cash);
        let allPayment = document.getElementById("paymentType");
        allPayment.appendChild(cardLabel);
        allPayment.appendChild(paypalLabel);
        allPayment.appendChild(cashLabel);
    }
    function handleChange(_event) {
        console.log(_event);
    }
    window.addEventListener("load", main);
})(grannystore || (grannystore = {}));
//# sourceMappingURL=main.js.map